# permissions for end users to view flavors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flavor-viewer-role
rules:
- apiGroups:
  - bundle.splunk.com
  resources:
  - flavors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bundle.splunk.com
  resources:
  - flavors/status
  verbs:
  - get
