# permissions for end users to edit installs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: install-editor-role
rules:
- apiGroups:
  - bundle.splunk.com
  resources:
  - installs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bundle.splunk.com
  resources:
  - installs/status
  verbs:
  - get
