# permissions for end users to view installs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: install-viewer-role
rules:
- apiGroups:
  - bundle.splunk.com
  resources:
  - installs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bundle.splunk.com
  resources:
  - installs/status
  verbs:
  - get
