# permissions for end users to view manifests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manifest-viewer-role
rules:
- apiGroups:
  - bundle.splunk.com
  resources:
  - manifests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bundle.splunk.com
  resources:
  - manifests/status
  verbs:
  - get
