---
apiVersion: v1
kind: ConfigMap
metadata:
  name: reg-proxy-nginx-configmap
  namespace: default
data:
  nginx.conf: |
    user  nginx;
    worker_processes  1;
    error_log  /var/log/nginx/error.log warn;
    pid        /tmp/nginx.pid;
    events {
        worker_connections  1024;
    }
    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;
      log_format  main  '$remote_addr - $remote_user [$time_local] "$request"'
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for" -uri=$uri -proxy-host=$proxy_host -request-uri=$request_uri';
      access_log  /var/log/nginx/access.log  main;
      sendfile        on;
      keepalive_timeout  65;
      server {
        listen __PORT__;
        resolver kube-dns.kube-system.svc.cluster.local valid=5s;


        location /healthz {
          return 200;
        }

        # forwards all the /v2/<registryname>/image:tag paths to registry-svc:5000/v2/image:tag
        location ~ ^\/v2\/?([^\/]*)\/?(.*) {
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "Upgrade";
          proxy_pass http://$1.__REGISTRY_NAMESPACE__.svc.cluster.local:5000/v2/$2;
          proxy_set_header Host $host;
          proxy_http_version 1.1;
        }


      }
    }
