---
apiVersion: v1
kind: Service
metadata:
  name: registry-{{ .RegistryName }}
  namespace: default
spec:
  ports:
    - port: 5000
      name: http
  selector:
    app: registry-{{ .RegistryName }}
